#!/usr/bin/env bash
# Builds code.js for the "Courier Design System" Figma plugin.
#
# The accent palettes are not typed in anywhere: they are computed here by
# running the app's own lib/theme.js, so the Figma variables are whatever the
# client would paint. Re-run after changing theme.js or color.js.
set -euo pipefail

here="$(cd "$(dirname "$0")" && pwd)"
root="$(cd "$here/../.." && pwd)"
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

# The client imports without extensions (Vite resolves them); Node's ESM loader
# does not, so the copies get explicit ".js" specifiers.
cp "$root"/client/src/lib/{theme,color,autotheme}.js "$tmp"/
perl -pi -e 's#from "(\./[A-Za-z]+)"#from "$1.js"#g' "$tmp"/*.js

node --input-type=module > "$tmp/data.json" <<EOF
const theme = await import("$tmp/theme.js");
const palettes = {};
for (const p of theme.PRESETS) {
  palettes[p.id] = theme.palette({ mode: "preset", preset: p.id, strength: theme.DEFAULT_STRENGTH });
}
console.log(JSON.stringify({
  presets: theme.PRESETS.map(({ id, name }) => ({ id, name })),
  palettes,
  strength: theme.DEFAULT_STRENGTH,
}));
EOF

python3 - "$here" "$root" "$tmp/data.json" <<'PY'
import base64, json, pathlib, sys
here, root, data = pathlib.Path(sys.argv[1]), pathlib.Path(sys.argv[2]), pathlib.Path(sys.argv[3])
mark = base64.b64encode((root / "client/public/courier-mark.png").read_bytes()).decode()
parts = [
    "/* GENERATED by docs/figma-ds/build.sh -- edit src/*.js and rebuild. */\n",
    "const DATA = " + data.read_text().strip() + ";\n",
    'const MARK_B64 = "' + mark + '";\n',
]
for src in sorted((here / "src").glob("*.js")):
    parts.append("\n/* ---- " + src.name + " ---- */\n" + src.read_text())
(here / "code.js").write_text("".join(parts))
PY

node --check "$here/code.js"
echo "wrote $here/code.js"
